### ISSUE TITLE
Dependencies version Error 

### ISSUE THREAD

**Issue by MrMoshkovitz** [suvelocity/Authentication-Challenge-TEMPLATE#1]
Hi, after running "npm i" in both the client and the root directory,
The react command "npm start" shows the following error:

![image](https://user-images.githubusercontent.com/50079480/95048866-4d60b300-06f1-11eb-97d4-e8beda4d294d.png)

The client cannot be run at all.
The challenge still works but the client experience is missing.

**Comment by Cyber4sPopo** [comment]
Fix for that will be to downgrade Jest in the root folder to 24.9.0

**Comment by david35008** [comment]
updated readme, we will solve the problem
