### ISSUE TITLE
status 400 or 401

### ISSUE THREAD

**Issue by AmirDebbie** [suvelocity/Authentication-Challenge-TEMPLATE#3]
POST path: "/users/logout", description: Logout Session.

Request template: body: {token: -refresh token-"}
server responses: status 200 "User Logged Out Successfully" | status 400 "Refresh Token Required" | status 400 "Invalid Refresh Token".

Are you sure both errors should be status 400? in other endpoints its 401 for "Refresh Token Required"

**Comment by david35008** [comment]
yes, because its not about authorization, its about the request itself. 
so if you send request without the token, to an endpoint that expect to get body with token, its a bad request
