### ISSUE TITLE
refresh or access?

### ISSUE THREAD

**Issue by AmirDebbie** [suvelocity/Authentication-Challenge-TEMPLATE#4]
GET path: /api/v1/users, description: Get users DB (admin only),

Request template: header {Authorization: "Bearer -access token-"}
Server Responses: status 200, body: {USERS: [...[{email, name, password, isAdmin}]} | status 401 "Refresh Token Required" | status 403 "Invalid Refresh Token".

does this get a refresh token or access?

**Comment by david35008** [comment]
you are right. fixed
