### ISSUE TITLE
INFORMATION of the USERS is not uniquely identified

### ISSUE THREAD

**Issue by ZBejavu** [suvelocity/Authentication-Challenge-TEMPLATE#5]
currently only the email of the user is a unique field.
so if each item in the INFORMATION array for all the users is represented by the name of the user, users with the same name will get their information mixed up.

![image](https://user-images.githubusercontent.com/67857471/95192343-bc660680-07da-11eb-986e-b2433c6e9aac.png)

**Comment by royc67** [comment]
thx, fixed.
