### ISSUE TITLE
Problematic for use with react router

### ISSUE THREAD

**Issue by AlonBru** [suvelocity/Authentication-Challenge-TEMPLATE#7]
if all the endpoints are not in one file, you cant use arrays for users and information, because both /users endpoints and /api endpoints need them.
one solution is using fs and .json files, but this creates a problem with reseting for tests and adding the users  - it seem to mess with the way bcrypt creates a hash

**Comment by ZBejavu** [comment]
This can fix your problem


![image](https://user-images.githubusercontent.com/67857471/95248549-2228b180-0820-11eb-87eb-3661420be09a.png)

![image](https://user-images.githubusercontent.com/67857471/95248666-4b494200-0820-11eb-8fb3-1520b0571b91.png)

**Comment by royc67** [comment]
Hi all, thank you for the notes.
There are many ways and good practices for implementing the RestFull API and storing data.
The purpose of this challenge is to understand and implement the token session authentication and its importance, Therefore using hard coded DB is good enough for this challenge.

**Comment by AlonBru** [comment]
Thanks for the suggestion, i'll try it later.
I fully understand that a hard coded db is enough.
it is simply quite frustrating to discover halfway through your work that you need to refractor everything because the arrays are needed for both end points. I don't think it benefits the challenge.
 most people work through the readme step by step, not reading everything in advance, and even if I did I could easily miss that.
It could be nice to warn the reader in advance, so they would know to skip using express router or indeed use your method if they'd like.
